### PR TITLE
Updating dependencies & revising early ML notebooks

### PR DESCRIPTION
**Pull request by bradleyboehmke**
- Added to, and reordered dependencies
- Updated dates in intro NB
- Made revisions to 02-model_training NB
- Deleted all old content in 04-feature_eng NB so I an start from scratch

### CODE REVIEW

**Comment by eswan18** [comment]
Sorry for taking so long to review this – I must have accidentally deleted the original email about the PR.

This looks really good! Love the intro notebook, it's a much better setup than we have for the other classes, particularly in terms of expectations. Thanks for putting that together.

Some small changes I'd request:
- In the intro notebook, you link out to the Introduction and Intermediate courses, but both links actually lead to the intermediate. The intro one should go to https://github.com/uc-python/intro-python-datasci
- In the intro notebook, there's a bullet about installing "pandas, scikit-learn, seaborn, keras, fuzzywuzzy, and gensim". I see you've updated the environment file, so this should probably be updated to match. For my sections, I don't anticipate needing anything outside Python and Conda.
- In 02, there's a line "Our Advanced Python workshop will go into much more detail than we have time for here." Probably not, since this *is* that workshop! I assume you probably copied that from old intermediate material.
- Typo in 02: "Don't feel intimated" – should be *intimidated*

A couple other random things I wanted to mention before we merge this:
- This isn't an issue, but I noticed that these aren't currently broken down into slides, so that's something we'll need to do as we get closer to the class.
- There's no way we can get through this 02 notebook in just an hour fifteen, right? Do we need to rearrange content to let this spill over to the following class day?

**Review by eswan18 — CHANGES_REQUESTED** [review]
See comments above

**Comment by eswan18** [comment]
Regarding the timing bit, I was looking at the schedule and we currently have sections for both "Modular Code" and "Modular Code & Unit Tests". We could drop the former, freeing up 9-10 on Thursday morning, and use that to extend the Model Training section – if you think that would be helpful.

**Comment by bradleyboehmke** [comment]
@eswan18 - I agree with your thoughts. I made changes to the introduction notebook based on your inputs and also due to the new date change.

And I completely refactored the 02 notebook. I decided to simplify and I broke it up into two notebooks:

- 02-explore_data.ipynb: This will also serve to provide a quick refresher on using Pandas for data exploration. I should be able to get through this notebook in 30-40 minutes.
- 03-first_model.ipynb: This provides a much shorter and more elementary introduction to using scikit-learn for modeling.  I took a lot of the content in the original 02-modeling_process notebook out as I think it was a bit overwhelming. I plan to work in the content I drop throughout future modules, which will provide a more subtle introduction to scikit-learn.  I should be able to get through this notebook in about 30 minutes.

**Pull request merged**
